In [1]:
!ls

drive  sample_data


In [2]:
%cd /content/drive/My Drive/PyHessian-master

/content/drive/My Drive/PyHessian-master


In [0]:
from archs.mnist import fc1
import torch
import numpy as np

In [0]:
model = fc1.fc1()

In [0]:
model = model.cuda()

In [6]:
model.load_state_dict(torch.load('/content/drive/My Drive/PyHessian-master/saves/fc1/mnist' + '/' + '0_model_lt.pth.tar').state_dict())

/usr/local/lib/python3.6/dist-packages/torch/serialization.py:593: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)


<All keys matched successfully>

In [7]:
model.eval()

fc1(
  (classifier): Sequential(
    (0): Linear(in_features=784, out_features=300, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=300, out_features=100, bias=True)
    (3): ReLU(inplace=True)
    (4): Linear(in_features=100, out_features=10, bias=True)
  )
)

In [11]:
model.parameters()[0]

TypeError: ignored

In [9]:
for layer in model.parameters():
  print(layer)

Parameter containing:
tensor([[ 1.9340e-40,  1.5183e-40,  1.9819e-40,  ...,  1.7710e-40,
          2.8647e-40, -1.0920e-40],
        [-1.5903e-40,  5.1381e-02,  5.1382e-02,  ...,  5.1381e-02,
         -4.9324e-41,  3.9156e-40],
        [ 5.1282e-40,  4.9252e-02, -4.6590e-41,  ...,  1.1703e-40,
         -4.4401e-40,  4.9251e-02],
        ...,
        [-9.7731e-41, -3.0260e-40,  1.5632e-40,  ...,  3.1876e-40,
         -4.7822e-40,  2.4020e-40],
        [ 4.3043e-40,  2.8253e-02,  2.0731e-40,  ...,  5.4797e-40,
          2.8252e-02,  2.8254e-02],
        [-6.8169e-41, -1.0474e-40,  5.3649e-40,  ..., -1.9695e-40,
          9.2877e-41,  1.7945e-40]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-2.0129e-37, -1.2432e-01, -9.8474e-02, -8.3115e-02,  1.0462e-01,
         1.6980e-01,  6.7545e-03, -1.2824e-01, -1.2883e-01, -1.6310e-02,
        -7.3069e-02, -1.3051e-01, -5.5082e-02, -1.0729e-01, -1.7688e-01,
         1.0115e-01, -8.7543e-02, -6.7733e-02,  9.3614e-38, -1.4202e

In [0]:
def get_params_grad(model):
    """
    get model parameters and corresponding gradients
    """
    params = []
    grads = []
    i = 0
    for param in model.parameters():
        if i != 0:
          continue
        if not param.requires_grad:
            continue
        params.append(param)
        grads.append(0. if param.grad is None else param.grad + 0.)
    return params, grads

In [0]:
params, grads = get_params_grad(model)

In [26]:
np.array(params)

array([Parameter containing:
tensor([[ 1.9340e-40,  1.5183e-40,  1.9819e-40,  ...,  1.7710e-40,
          2.8647e-40, -1.0920e-40],
        [-1.5903e-40,  5.1381e-02,  5.1382e-02,  ...,  5.1381e-02,
         -4.9324e-41,  3.9156e-40],
        [ 5.1282e-40,  4.9252e-02, -4.6590e-41,  ...,  1.1703e-40,
         -4.4401e-40,  4.9251e-02],
        ...,
        [-9.7731e-41, -3.0260e-40,  1.5632e-40,  ...,  3.1876e-40,
         -4.7822e-40,  2.4020e-40],
        [ 4.3043e-40,  2.8253e-02,  2.0731e-40,  ...,  5.4797e-40,
          2.8252e-02,  2.8254e-02],
        [-6.8169e-41, -1.0474e-40,  5.3649e-40,  ..., -1.9695e-40,
          9.2877e-41,  1.7945e-40]], device='cuda:0', requires_grad=True),
       Parameter containing:
tensor([-2.0129e-37, -1.2432e-01, -9.8474e-02, -8.3115e-02,  1.0462e-01,
         1.6980e-01,  6.7545e-03, -1.2824e-01, -1.2883e-01, -1.6310e-02,
        -7.3069e-02, -1.3051e-01, -5.5082e-02, -1.0729e-01, -1.7688e-01,
         1.0115e-01, -8.7543e-02, -6.7733e-02,  9.361